# AUTO-GENERATED by src/ttdas_export.py -- do not edit by hand.
# Source : examples\sample_5min_actions.json
# Map    : data\ttdas_device_map.json
# Policy : status on/off -> one <device>_on_off toggle recording; brightness/
#          light_temp have no click recording and are skipped; co-timed actions
#          get ascending :SS. See src/ttdas_export.py for details.
# Scheduled: 5 action(s); skipped: 1.
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from ttdas import schedule_at, run, driver


def status_aidot_lamp_on_off():
    driver.launchApp('com.aidot.aidot')
    driver.replay_recording('aidot_lamp_on_off')
    driver.replay_recording('clear_cache')
    driver.stopApp('com.aidot.aidot')


def status_shelly_relais_on_off():
    driver.launchApp('cloud.shelly.smartcontrol')
    driver.replay_recording('shelly_relais_on_off')
    driver.replay_recording('clear_cache')
    driver.stopApp('cloud.shelly.smartcontrol')


def status_tapo_socket_on_off():
    driver.launchApp('com.tplink.kasa_android')
    driver.replay_recording('tapo_socket_on_off')
    driver.replay_recording('clear_cache')
    driver.stopApp('com.tplink.kasa_android')


def status_tuya_lamp_on_off():
    driver.launchApp('com.tuya.smart')
    driver.replay_recording('tuya_lamp_on_off')
    driver.replay_recording('clear_cache')
    driver.stopApp('com.tuya.smart')


if __name__ == "__main__":
    schedule_at('06:00:00', status_aidot_lamp_on_off)
    schedule_at('06:01:00', status_shelly_relais_on_off)
    schedule_at('06:03:00', status_tapo_socket_on_off)
    schedule_at('06:03:01', status_tuya_lamp_on_off)
    schedule_at('06:05:00', status_shelly_relais_on_off)
    # skipped (no toggle recording / unmapped):
    #   06:00 aidot_lamp.brightness: no click recording (skipped)
    run()
