"""Aufgabe 3: turn a Stage-3 activity JSON into an executable TTDAS script.

Reads a Stage-3 ``stage3_actions.json`` (the schema-validated device actions) and
a device map (``data/ttdas_device_map.json``) and emits a runnable Python script
that mirrors slide 16 of the assignment: one function per device toggle that does
``launchApp -> replay_recording(<device>_on_off) -> replay_recording('clear_cache')
-> stopApp``, scheduled with ``schedule_at('HH:MM:SS', func)``.

Design decisions (documented for the report):
* **Recording collapse.** TTDAS has ONE click recording per device that toggles
  its power (slide 16, ``<device>_on_off``); it does not encode on vs. off. So
  every ``status`` action (on OR off) maps to that single recording.
* **Skip non-toggle actions.** The lab uses simple click recordings only (slide
  15: warm/cool, not 2700-6500K), so ``brightness`` / ``light_temp`` have no
  recording in the map and are skipped (and logged), unless the map declares one.
* **HH:MM -> HH:MM:SS.** Stage-3 timestamps are HH:MM and several actions can
  share a minute; ``schedule_at`` needs HH:MM:SS, so co-timed actions are
  de-collided by assigning ascending seconds in chronological order.
* **Fail loud / skip.** Unmapped devices abort under ``--strict`` (default) so the
  script never references a recording that does not exist; without ``--strict``
  they are skipped and logged.

Usage:
    python -m src.ttdas_export --in outputs/run_1d/day_01/stage3_actions.json \\
        --out examples/ttdas_run1d_day01.py [--window 06:00-06:05] [--no-strict]
"""
from __future__ import annotations

import argparse
from pathlib import Path

from .context import resolve_data_dir
from .io_utils import load_config, read_json, unwrap_actions, write_text
from .validator import parse_window, validate_actions, error_messages


def _load_actions(path: Path) -> list[dict]:
    """Load actions from a stage3_actions.json file or a run/day directory."""
    if path.is_dir():
        cand = path / 'stage3_actions.json'
        if not cand.exists():
            cand = path / 'day_01' / 'stage3_actions.json'
        path = cand
    return unwrap_actions(read_json(path))


def _minute(ts: str) -> int | None:
    parts = ts.split(':') if isinstance(ts, str) else []
    if len(parts) >= 2 and parts[0].isdigit() and parts[1].isdigit():
        return int(parts[0]) * 60 + int(parts[1])
    return None


def build_script(actions: list[dict], device_map: dict, rel_to_root: str,
                 source: str, map_path: str, strict: bool) -> tuple[str, dict]:
    """Return (script_text, stats). Raises ValueError on unmapped device when strict."""
    # chronological order; stable for equal timestamps
    ordered = sorted(
        [a for a in actions if _minute(a.get('timestamp', '')) is not None],
        key=lambda a: _minute(a['timestamp']),
    )

    funcs: dict[str, tuple[str, str]] = {}   # func_name -> (app, recording)
    scheduled: list[tuple[str, str]] = []    # (HH:MM:SS, func_name)
    skipped: list[str] = []
    sec_counter: dict[int, int] = {}

    for a in ordered:
        device = a.get('device')
        action = a.get('action')
        ts = a.get('timestamp')
        entry = device_map.get(device)
        if entry is None:
            msg = f"{ts} {device}.{action}: device not in map"
            if strict:
                raise ValueError(f'Unmapped device {device!r}; add it to the map or use --no-strict.')
            skipped.append(msg)
            continue
        rec = (entry.get('recordings') or {}).get(action)
        if not rec:
            skipped.append(f"{ts} {device}.{action}: no click recording (skipped)")
            continue
        name = f'{action}_{rec}'
        funcs.setdefault(name, (entry['app'], rec))
        mod = _minute(ts)
        idx = sec_counter.get(mod, 0)
        sec_counter[mod] = idx + 1
        # de-collide co-timed actions with ascending seconds; if a single minute
        # holds >60 actions, roll the overflow into the following minute(s) so
        # every emitted HH:MM:SS stays unique and ascending.
        total = mod * 60 + idx
        hh, mm, ss = (total // 3600) % 24, (total % 3600) // 60, total % 60
        scheduled.append((f'{hh:02d}:{mm:02d}:{ss:02d}', name))

    lines: list[str] = []
    lines.append('# AUTO-GENERATED by src/ttdas_export.py -- do not edit by hand.')
    lines.append(f'# Source : {source}')
    lines.append(f'# Map    : {map_path}')
    lines.append('# Policy : status on/off -> one <device>_on_off toggle recording; brightness/')
    lines.append('#          light_temp have no click recording and are skipped; co-timed actions')
    lines.append('#          get ascending :SS. See src/ttdas_export.py for details.')
    lines.append(f'# Scheduled: {len(scheduled)} action(s); skipped: {len(skipped)}.')
    lines.append('import os')
    lines.append('import sys')
    lines.append('')
    lines.append(f'sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), {rel_to_root!r})))')
    lines.append('from ttdas import schedule_at, run, driver')
    lines.append('')
    lines.append('')
    for name in sorted(funcs):
        app, rec = funcs[name]
        lines.append(f'def {name}():')
        lines.append(f'    driver.launchApp({app!r})')
        lines.append(f'    driver.replay_recording({rec!r})')
        lines.append("    driver.replay_recording('clear_cache')")
        lines.append(f'    driver.stopApp({app!r})')
        lines.append('')
        lines.append('')
    lines.append('if __name__ == "__main__":')
    for timestr, name in scheduled:
        lines.append(f'    schedule_at({timestr!r}, {name})')
    if skipped:
        lines.append('    # skipped (no toggle recording / unmapped):')
        for s in skipped:
            lines.append(f'    #   {s}')
    lines.append('    run()')
    lines.append('')

    stats = {'scheduled': len(scheduled), 'skipped': len(skipped), 'funcs': len(funcs)}
    return '\n'.join(lines), stats


def main() -> None:
    parser = argparse.ArgumentParser(description='Export a Stage-3 actions JSON to an executable TTDAS script.')
    parser.add_argument('--in', dest='inp', required=True, help='stage3_actions.json file or run/day dir.')
    parser.add_argument('--out', required=True, help='Output .py path.')
    parser.add_argument('--map', dest='map_path', default=None, help='Device map JSON (default: data/ttdas_device_map.json).')
    parser.add_argument('--data-dir', default=None, help='Constellation data dir for schema validation (default: config data_dir).')
    parser.add_argument('--window', default=None, help='Optional HH:MM-HH:MM slice (e.g. 06:00-06:05 for the 5-minute example).')
    parser.add_argument('--no-strict', dest='strict', action='store_false', help='Skip+log unmapped devices instead of aborting.')
    parser.set_defaults(strict=True)
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    config = load_config(root)
    files = config['files']
    data_dir = resolve_data_dir(root, config, args.data_dir)
    map_path = Path(args.map_path) if args.map_path else root / 'data' / 'ttdas_device_map.json'
    if not map_path.is_absolute():
        map_path = root / map_path

    actions = _load_actions(Path(args.inp))
    device_map = {k: v for k, v in read_json(map_path).items() if not k.startswith('_')}

    # Optional 5-minute slice.
    win = parse_window(args.window) if args.window else None
    if win is not None:
        actions = [a for a in actions if (m := _minute(a.get('timestamp', ''))) is not None and win[0] <= m <= win[1]]

    # Pre-export sanity check against the device schema (advisory).
    devices = read_json(data_dir / files['devices'])
    verr = validate_actions(actions, devices)
    if verr:
        print(f'WARNING: {len(verr)} validation issue(s) in the input actions:')
        for msg in error_messages(verr)[:10]:
            print(f'  - {msg}')

    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = root / out_path
    try:
        rel = _rel_to_root(out_path, root)
    except ValueError:
        # --out on a different Windows drive than the repo: emit an absolute insert
        # (os.path.join drops its first arg when the second is absolute).
        rel = str(root)

    script, stats = build_script(actions, device_map, rel, source=str(Path(args.inp)),
                                 map_path=str(map_path.relative_to(root)) if str(map_path).startswith(str(root)) else str(map_path),
                                 strict=args.strict)
    write_text(out_path, script)
    print(f'Wrote {out_path} -- {stats["scheduled"]} scheduled action(s), '
          f'{stats["funcs"]} TTDAS func(s), {stats["skipped"]} skipped.')


def _rel_to_root(out_path: Path, root: Path) -> str:
    """POSIX relative path from the output file's dir to the repo root (for sys.path)."""
    import os
    return os.path.relpath(root, out_path.parent).replace('\\', '/')


if __name__ == '__main__':
    main()
